"""Initial Audit schema

Revision ID: 0fac592358f5
Revises:
Create Date: 2026-02-10 12:47:15.895282

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0fac592358f5"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "change_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("table_name", sa.String(length=150), nullable=False),
        sa.Column("record_id", sa.String(length=100), nullable=False),
        sa.Column("operation", sa.String(length=20), nullable=False),
        sa.Column("changed_by", sa.BigInteger(), nullable=True),
        sa.Column(
            "changed_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("old_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("new_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("changed_fields", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("source", sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="AUDIT",
    )
    op.create_table(
        "audit_templates",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["public.employee.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["public.employee.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="AUDIT",
    )
    op.create_table(
        "master_data",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("type", sa.String(length=100), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["public.employee.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["public.employee.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="AUDIT",
    )
    op.create_table(
        "audit_areas",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("template_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("weightage", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["public.employee.id"],
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["AUDIT.audit_templates.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["public.employee.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="AUDIT",
    )
    op.create_table(
        "audit_project_templates",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.BigInteger(), nullable=False),
        sa.Column("template_id", sa.UUID(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["public.employee.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["public.projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["AUDIT.audit_templates.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["public.employee.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="AUDIT",
    )
    op.create_table(
        "audits",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("template_id", sa.UUID(), nullable=False),
        sa.Column("scheduled_date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("overall_score", sa.Integer(), nullable=True),
        sa.Column("rag_status", sa.String(length=10), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["public.employee.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["public.projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["AUDIT.audit_templates.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["public.employee.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="AUDIT",
    )
    op.create_table(
        "employee_role_mappings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["public.employee.id"],
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["public.employee.id"],
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["AUDIT.master_data.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["public.employee.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="AUDIT",
    )
    op.create_table(
        "audit_participants",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("audit_id", sa.UUID(), nullable=True),
        sa.Column("employee_id", sa.BigInteger(), nullable=True),
        sa.Column("role_type", sa.String(length=50), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["audit_id"],
            ["AUDIT.audits.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["public.employee.id"],
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["public.employee.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["public.employee.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="AUDIT",
    )
    op.create_table(
        "audit_report_snapshots",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("audit_id", sa.UUID(), nullable=True),
        sa.Column("overall_score", sa.Integer(), nullable=True),
        sa.Column("rag_status", sa.String(length=10), nullable=True),
        sa.Column("report_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["audit_id"],
            ["AUDIT.audits.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["public.employee.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["public.employee.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("audit_id"),
        schema="AUDIT",
    )
    op.create_table(
        "audit_scopes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("area_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["area_id"],
            ["AUDIT.audit_areas.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["public.employee.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["public.employee.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="AUDIT",
    )
    op.create_table(
        "audit_questions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("scope_id", sa.UUID(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("percentage", sa.Integer(), nullable=False),
        sa.Column("is_mandatory", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["public.employee.id"],
        ),
        sa.ForeignKeyConstraint(
            ["scope_id"],
            ["AUDIT.audit_scopes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["public.employee.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="AUDIT",
    )
    op.create_table(
        "audit_action_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("audit_id", sa.UUID(), nullable=True),
        sa.Column("audit_question_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("owner_id", sa.BigInteger(), nullable=True),
        sa.Column("priority", sa.String(length=50), nullable=True),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["audit_id"],
            ["AUDIT.audits.id"],
        ),
        sa.ForeignKeyConstraint(
            ["audit_question_id"],
            ["AUDIT.audit_questions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["public.employee.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["public.employee.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["public.employee.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="AUDIT",
    )
    op.create_table(
        "audit_question_options",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("question_id", sa.UUID(), nullable=False),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.Column("value", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["public.employee.id"],
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["AUDIT.audit_questions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["public.employee.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="AUDIT",
    )
    op.create_table(
        "audit_responses",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("audit_id", sa.UUID(), nullable=False),
        sa.Column("question_id", sa.UUID(), nullable=False),
        sa.Column("selected_option_id", sa.UUID(), nullable=True),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("recommendation", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["audit_id"],
            ["AUDIT.audits.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["public.employee.id"],
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["AUDIT.audit_questions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["selected_option_id"],
            ["AUDIT.audit_question_options.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["public.employee.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="AUDIT",
    )
    op.create_table(
        "audit_evidences",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("response_id", sa.UUID(), nullable=True),
        sa.Column("evidence_type", sa.String(length=20), nullable=True),
        sa.Column("file_url", sa.Text(), nullable=True),
        sa.Column("original_file_name", sa.String(length=255), nullable=True),
        sa.Column("mime_type", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["public.employee.id"],
        ),
        sa.ForeignKeyConstraint(
            ["response_id"],
            ["AUDIT.audit_responses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["public.employee.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="AUDIT",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("audit_evidences", schema="AUDIT")
    op.drop_table("audit_responses", schema="AUDIT")
    op.drop_table("audit_question_options", schema="AUDIT")
    op.drop_table("audit_action_items", schema="AUDIT")
    op.drop_table("audit_questions", schema="AUDIT")
    op.drop_table("audit_scopes", schema="AUDIT")
    op.drop_table("audit_report_snapshots", schema="AUDIT")
    op.drop_table("audit_participants", schema="AUDIT")
    op.drop_table("employee_role_mappings", schema="AUDIT")
    op.drop_table("audits", schema="AUDIT")
    op.drop_table("audit_project_templates", schema="AUDIT")
    op.drop_table("audit_areas", schema="AUDIT")
    op.drop_table("master_data", schema="AUDIT")
    op.drop_table("audit_templates", schema="AUDIT")
    op.drop_table("change_logs", schema="AUDIT")
    # ### end Alembic commands ###
